# Generated by Django 5.2 on 2025-04-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caffino', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='weight',
        ),
    ]
