# Generated by Django 5.2 on 2025-05-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caffino', '0006_alter_cartitem_quantity_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'تصویر بنر',
                'verbose_name_plural': 'تصاویر بنر',
                'ordering': ['order'],
            },
        ),
    ]
