# Generated by Django 5.2 on 2025-05-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caffino', '0007_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
