# Generated by Django 5.2 on 2025-05-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caffino', '0009_alter_user_is_superuser_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='default_user', max_length=150, null=True, unique=True),
        ),
    ]
