# Generated by Django 5.2 on 2025-05-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caffino', '0011_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerimage',
            options={},
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='alt_text',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ترتیب'),
        ),
    ]
