# Generated by Django 5.2 on 2025-05-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caffino', '0012_alter_bannerimage_options_alter_bannerimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
