# Generated by Django 5.2 on 2025-05-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caffino', '0013_alter_bannerimage_is_active_alter_bannerimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'امتیاز', 'verbose_name_plural': 'امتیازات'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید شده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت (تومان)'),
        ),
    ]
